package com.mofaia.mypay.app.constant

const val RETROFIT_BUILDER_DEFAULT = "RETROFIT_BUILDER_DEFAULT"
const val FIRESTORE_DATA_SOURCE = "firestoreDataSource"
const val FIRESTORE_COLLECTION_QUOTATIONS = "COLLECTION_QUOTATIONS"
const val QUOTATIONS_FIRESTORE_DATA_SOURCE = "QUOTATIONS_FIRESTORE_DATA_SOURCE"
const val QUOTATIONS_BITCOIN_DATA_SOURCE = "QUOTATIONS_BITCOIN_DATA_SOURCE"
const val QUOTATIONS_BRITA_DATA_SOURCE = "QUOTATIONS_BRITA_DATA_SOURCE"
const val QUOTATIONS_REPOSITORY = "QUOTATIONS_REPOSITORY"
