package com.mofaia.mypay.app.constant

const val RETROFIT_BUILDER_DEFAULT = "RETROFIT_BUILDER_DEFAULT"
const val FIRESTORE_COLLECTION_QUOTATIONS = "COLLECTION_QUOTATIONS"
const val QUOTATIONS_FIRESTORE_DATA_SOURCE = "QUOTATIONS_FIRESTORE_DATA_SOURCE"
const val QUOTATIONS_REPOSITORY = "QUOTATIONS_REPOSITORY"

const val FIRESTORE_COLLECTION_WALLET = "COLLECTION_WALLET"
const val WALLET_FIRESTORE_DATA_SOURCE = "WALLET_FIRESTORE_DATA_SOURCE"
const val WALLET_REPOSITORY = "WALLET_REPOSITORY"